### ISSUE TITLE
Filter performance issue with Angular 20

### ISSUE THREAD

**Issue by Valoutre** [ali-hm/angular-tree-component#14]
## Minimal reproduction of the bug/regression with instructions:

- Angular 19 version (working) : https://stackblitz.com/edit/stackblitz-starters-qgxemcez?file=package.json 
- Angular 20 version (crashing) : https://stackblitz.com/edit/stackblitz-starters-wbbxx9tx?file=package.json
- Angular 21 version (crashing) : https://stackblitz.com/edit/stackblitz-starters-ajtiask5?file=package.json

## Expected behavior:

Filter performance on huge dataset should not cause app to crash.

## Versions of Angular Tree Component, Angular, Node, affected browser(s) and operating system(s):

- Angular Tree Component 20.3.4
- Angular 20.3.14

## Other information:

As temporary fix, Angular Tree Component 19.2.5 + Angular 20.3.14 works as intended.
I Can provide any other information if needed.

## I would be willing to submit a PR to fix this issue

[ ] Yes (Assistance will be provided if you need help to submit a pull request)
[X] No

**Comment by ali-hm** [comment]
give a try to version 21 and let me know if it is still crashing or not.

**Comment by Valoutre** [comment]
Added to the original post, it crash too

**Comment by ali-hm** [comment]
give a try to v21.0.2, it should fix the issue

**Comment by Valoutre** [comment]
Its not crashing but it's very very slow and still freeze on input. 
I think this is linked to the "dictionary => signal" migration. Maybe some effects are triggered too much.

**Comment by rubiesonthesky** [comment]
I think it’s possible that some effects are triggered too much. The version 20.3.4 is unusable for me because Angular complains about circular effect triggering. Luckily 20.3.3 seems to be working with Angular 21. 
Angular just published new effect guide which states that effects should be rarely used and only for side effects like localstorage and logging.  Ref https://github.com/angular/angular/blob/827f5a6fd5bb35a07d16f3af3e8a35662d220630/adev/src/content/guide/signals/effect.md

> Avoid using effects for propagation of state changes. This can result in `ExpressionChangedAfterItHasBeenChecked` errors, infinite circular updates, or unnecessary change detection cycles.
Instead, use computed signals to model state that depends on other state.

**Comment by ali-hm** [comment]
Due to lack of time i appreciate some help on this matter.

**Comment by AntonChesnokov** [comment]
Since that were my changes, I'll take a look at the problem today.
Interesting that I was testing demo examples with virtual scrolling and they were fine

**Comment by AntonChesnokov** [comment]
@ali-hm  I've just opened a PR with a fix. 
https://github.com/ali-hm/angular-tree-component/pull/15

@Valoutre  I also included your stackblitz example to list of project examples, so you can build the lib and test the demo.

As soon as it's merged we can cherry pick the fix to Angular 20 release

**Comment by Valoutre** [comment]
Fixed with the 21.0.3. Thank you !

**Comment by tutam1232** [comment]
> [@ali-hm](https://github.com/ali-hm) I've just opened a PR with a fix. [#15](https://github.com/ali-hm/angular-tree-component/pull/15)
> 
> [@Valoutre](https://github.com/Valoutre) I also included your stackblitz example to list of project examples, so you can build the lib and test the demo.
> 
> As soon as it's merged we can cherry pick the fix to Angular 20 release

Hi, can this fix be also cherry-picked to Angular 20 release? We are migrating our app to Angular 20 and got the same issue. We've not yet planned for upgrading our app to Angular 21. Therefore, it would be great if we also have the fix for Angular 20. Thanks!
